### ISSUE TITLE
Ways of running and packaging games

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#10]
I have to run the game by invoking the shell and typing `tophat debug`. I would like to run it by just clicking `tophat.exe` in the folder. But when I do it, it prints `Could not initialize umka` and does not run anything.

**Comment by marekmaskarinec** [comment]
Yes that is intended, although it probably isn't the best solution. Currently is searches for `tophat.dat/game.um`, if you don't specify the `debug` flag. On linux, you can use `tophat run`, but a gui tool is still being worked on. I will make it, so it searches for `game.um` in current directory and if it isn't there, it will look into `tophat.dat`.

**Comment by marekmaskarinec** [comment]
Fixed in https://github.com/marekmaskarinec/tophat/commit/27c61fb66ebf996ca261fd073708e07cce4d8e29

**Comment by marekmaskarinec** [comment]
I added a gui tool in https://github.com/marekmaskarinec/tophat/commit/c8f4a93a7fc801266ac6b4374cb15fb5343b45a0

**Comment by vtereshkov** [comment]
Don't understand how to use it. Is it for packaging games with tophat? What "workspace" should I open?

By the way, sometimes it hangs.

![image](https://user-images.githubusercontent.com/52492460/114322118-2ca56a00-9b27-11eb-9514-2ec0c80b18de.png)

**Comment by marekmaskarinec** [comment]
You need to install tophat using `install.bat` in the `win-package.zip` file. The you will open a new directory, use init and you will get a working hello world example. It mainly serves, so you don't have to copy files around like the exe. Soon, I will be fixing the packaging and add an option similar to cli tool's `libs` option.

> By the way, sometimes it hangs.
I have no idea at all, why it is doing that. It doesn't panic or anything. I'll try doing some debugging.

**Comment by vtereshkov** [comment]
Release 0.1 is not working under Windows because `install.bat` copies two `.um` files to the _current_ folder, while `tophat-gui.exe` is expecting to find them in the user profile folder. So on clicking `init` I get this error:

![image](https://user-images.githubusercontent.com/52492460/114929948-207a1f00-9e3d-11eb-809a-f85793fdaced.png)

**Comment by marekmaskarinec** [comment]
Interesting. Is the

**Comment by marekmaskarinec** [comment]
What if you replace the variable with `%HOMEPATH%?

**Comment by vtereshkov** [comment]
The only way to have the `*.um` files in that folder is to use the following script:
```
mkdir %HOMEPATH%\Documents\tophat\
copy /Y tophat\*.* %HOMEPATH%\Documents\tophat
```
So I have
```
C:\Users\Vasiliy\Documents\tophat>dir
15.04.2021  23:20    <DIR>          .
15.04.2021  23:20    <DIR>          ..
15.04.2021  22:06               375 game.um
15.04.2021  22:06               117 global.um
```
But that's not enough. I get another error:

![image](https://user-images.githubusercontent.com/52492460/114933684-9f715680-9e41-11eb-8aa2-2b74425196f5.png)

Is the problem with the `*` placeholders in names?

**Comment by vtereshkov** [comment]
By the way, on Linux I also get an error:
```
vtereshkov@vtereshkov-ubuntupc:~/tophat-release/hello$ ./tophat run
/usr/share/tophat/bin/tophat-linux: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/tophat/bin/tophat-linux)
```
I suppose I have to manually update the C standard library.

**Comment by marekmaskarinec** [comment]
Now this is interesting. I think, I got this same error with other program today (I have 2.33).

As for the window issue, I probably need to copy the two files separately. I will look into it tomorrow.

**Comment by vtereshkov** [comment]
And yes, the Windows GUI tool still hangs sometimes.

**Comment by marekmaskarinec** [comment]
Hmm. I have no idea why. I will probably rewrite it to use either fyne, or in umka.

**Comment by marekmaskarinec** [comment]
Another way is to just distribute the exe. Now it's actually a possible solution, since you don't have to deal with the libraries. The whole windows thing is hard for me, since I don't have easy access to a windows machine.

**Comment by vtereshkov** [comment]
I like this approach very much! Now the installation and deployment seems to be harder than writing games.

**Comment by marekmaskarinec** [comment]
The exe is still there. When you download it, it should be located: `tophat-win/tophat/bin/tophat-win.exe`.

**Comment by vtereshkov** [comment]
Cool! But I cannot see what makes my HPs decrease. And - again - the game crashes on exit.

**Comment by marekmaskarinec** [comment]
Your hp is lowered, when enemy ships decrease bellow the screen.

When does the crash happen and what does it do?

**Comment by vtereshkov** [comment]
It crashes when I close the window with the cross. When I click `Quit`, it exits normally.
The other problem is that when I click `To menu`, the `Quit` button also receives this event and causes the game to exit.

**Comment by marekmaskarinec** [comment]
> It crashes when I close the window with the cross.
This is a known issue and frankly, I have no idea, how to solve it. Rawdraw is using `atexit` for the `HandleDestroy` function, so I don't have a way for umka to exit.

> The other problem is that when I click To menu, the Quit button also receives this event and causes the game to exit.

This seems to be a crash in `audio.c`. What is even happening there? It somehow deletes the sound array (keeping the sound count). I don't know, why that happens, but today I made a small change to audio.um, so that might be it. I still have no idea why.

**Comment by vtereshkov** [comment]
> This is a known issue and frankly, I have no idea, how to solve it.

It seemed to me you solved it in RAIDER.

By the way, `tophat-gui.exe` has just been removed by my antivirus.

**Comment by marekmaskarinec** [comment]
In the last commit, I've done some fixes to audio. It _shouldn't_ crash now.

> By the way, tophat-gui.exe has just been removed by my antivirus.

I checked it for viruses, and there aren't any. I'm not sure, why that is happening, but I think, I'm gonna have to rethink the way of interacting with the engine on windows entirely.

**Comment by vtereshkov** [comment]
> In the last commit, I've done some fixes to audio. It shouldn't crash now.

Cannot run `make` to rebuild it: `embedder` is not found.

> I checked it for viruses, and there aren't any.

Of course there aren't. But you know, modern antiviruses have AI-based heuristics to detect viruses that have never been seen before. This causes an enormous amount of false positives. I have had a lot of such problems with my previous (native x86) compiler project. 

Unfortunately, there is no solution. A demotivating discussion with the designers of Go: https://github.com/golang/go/issues/21611

**Comment by marekmaskarinec** [comment]
Soryy. The embedder still isn't included in the repo. You can edit the makefile, so it doesn't run it and doesn't compil with `RELEASE_BUILD`. Then you will have to copy the libraties though.

**Comment by vtereshkov** [comment]
Do you have an up-to-date `umkalibs.h`?

**Comment by marekmaskarinec** [comment]
Here
[umkalibs.zip](https://github.com/marekmaskarinec/tophat/files/6325084/umkalibs.zip)

**Comment by vtereshkov** [comment]
Looks like you are trying to free `respath` that has been allocated on the stack rather than in the heap:
```
	char rp[255];
	respath = &rp[0];
	...
	free(respath);
```
Moreover, you don't check if `destroyfunc == -1`.

**Comment by marekmaskarinec** [comment]
I tried fixing that. I also added the embedder, so you can build it on your own.

For windows support, I got an idea. You would download a zip file, containing the two preset scripts and tophat exe. You would extract that somewhere, every time, you want to make a game. I'm just scared, people wouldn't package for linux, since it would be tedious process. Maybe adding a package program, you just run in a directory with both binaries embedded in it. Just an idea.

**Comment by vtereshkov** [comment]
Now I'm reinstalling Go to compile your `embedder`, since it is incompatible with Go 1.13.

I think the easiest way to make a game with tophat is just to copy `tophat.exe` into the folder that contains the game modules. This approach is simple and reliable. All "build systems" that depend on additional tools, user profiles, workspaces are too difficult to comprehend and error-prone. Yes, I still don't understand what a tophat workspace is, what to do with the GUI tool and where it copies its files.

**Comment by marekmaskarinec** [comment]
> Now I'm reinstalling Go to compile your embedder, since it is incompatible with Go 1.13.

Do you want to send the binary?

> folder that contains the game modules

You don't need that anymore, since all modules are embedded.

> All "build systems" that depend on additional tools, user profiles, workspaces are too difficult to comprehend and error-prone

That is a good point. I will just do the zip file, you can extract for easy start.

**Comment by vtereshkov** [comment]
> Do you want to send the binary?

Yes, I do. Neither `Makefile` nor `embedder` itself work properly under Windows:
```
@if [ ! -f cmd/embedder/embedder ]; then echo "please build embedder by running go build in cmd/embedder"; exit 1; fi
Unexpected !

./cmd/embedder/embedder text umka/*.um umka/std/std.um >> src/umkalibs.h
. is not a program
```
When I manually copy `embedder.exe` to the tophat root folder, it produces a broken file:
```
"#ifndef UMKALIBS_H\n#define UMKALIBS_H\nconst char *libs[] = {" 
open umka/*.um: The filename, directory name, or volume label syntax is incorrect.
"\n"
,
...
```
> You don't need that anymore, since all modules are embedded.

I mean the modules that contain the game itself, not tophat modules or Umka standard library.

**Comment by vtereshkov** [comment]
But yes, when I copy the prepared `umkalibs.h` and remove `embedder` lines from `Makefile`, I get `tophat` that exits normally.

**Comment by marekmaskarinec** [comment]
[embedder.zip](https://github.com/marekmaskarinec/tophat/files/6327564/embedder.zip)

I updated the makefile to list all needed files. I still don't know, how to do platform specific code in makefile, so please add `.exe` on line 73. The embedder binary should be in `cmd/embedder`.

**Comment by vtereshkov** [comment]
No success:
```
C:\Users\Vasiliy\Desktop\tophat>mingw32-make windows
#@if [ ! -f cmd/embedder/embedder ]; then echo "please build embedder by running go build in cmd/embedder"; exit 1; fi
process_begin: CreateProcess(NULL, #@if [ ! -f cmd/embedder/embedder ]; then echo "please build embedder by running go b
uild in cmd/embedder;" exit 1; fi, ...) failed.
make (e=2): ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.
mingw32-make: *** [Makefile:71: libembed] Error 2
```
I can run `embedder` manually with the same command line args, but the file it produces is still incorrect, since it doesn't distinguish between C-syntax lines without quotes and Umka-syntax lines in quotes.

**Comment by marekmaskarinec** [comment]
> I can run embedder manually with the same command line args, but the file it produces is still incorrect, since it doesn't distinguish between C-syntax lines without quotes and Umka-syntax lines in quotes.

I'm not sure, if I understand. What exactly is the problem. Also try deleting that line with the if completely.

**Comment by vtereshkov** [comment]
At last I know how to do it correctly on Windows:
```
libembed:
	echo #ifndef UMKALIBS_H >> src/umkalibs.h
	echo #define UMKALIBS_H >> src/umkalibs.h
	echo const char *libs[] = { >> src/umkalibs.h
	cmd\embedder\embedder text umka/animation.um umka/audio.um umka/entity.um umka/image.um umka/input.um umka/map.um umka/misc.um umka/polygon.um umka/rawdraw.um umka/raycast.um umka/rectangle.um umka/tophat.um umka/ui.um umka/vec.um umka/std/std.um >> src/umkalibs.h
	echo }; >> src/umkalibs.h
	echo #endif >> src/umkalibs.h
```

**Comment by marekmaskarinec** [comment]
Interesting. That seems like a problem between linux and windows. I'm not sure, how I can implement your solution. On linux, it will take the `#` as a comment, since it isn't inside `"`. I will try doing some platform specific stuff in the Makefile.

Btw, I think, the first line needs to use `>` not `>>`, since you want to clear the file every time you make it.

**Comment by vtereshkov** [comment]
> Btw, I think, the first line needs to use > not >>, since you want to clear the file every time you make it.

Yes, you're probably right. But all other things like quotes or backslashes are important. As for carriage returns, I don't know how to echo them in one line on Windows (maybe it's somehow possible).

**Comment by marekmaskarinec** [comment]
The current embedder replaces backslashes with double backslashes, if that's, what you mean.

**Comment by vtereshkov** [comment]
I mean using backslashes instead of slashes in paths.

**Comment by vtereshkov** [comment]
While the packaging problem on Windows is unresolved, I think it may be a good trade-off to embed all the tophat modules into the release binary but keep all game modules as separate files. I use this configuration for running your space shooter and it's really convenient, except for hiding the game source from the competitors' eyes :) I just put a single binary into a folder with the game modules and run it.

**Comment by marekmaskarinec** [comment]
Yes. That is currently the way to do it. I still want to make an option to build it and embed the files. Not as much to hide the source code, but so the binary is free standing and could eventually be used on platforms without access to the fs (web).

As for windows support, I think I have an idea that might work. A simple zip file with both linux binaries and two (maybe more) batch scripts. You would extract it anywhere you like. If you wanted to start a project, you would run init.bat. That would make you a directory with an exe and the hello world file. Another would be for packaging. I'm still not quite sure, what to focus on right now. The thing, I talked about sounds easy, so I will do that first and the remove all dependencies on go.

**Comment by marekmaskarinec** [comment]
> A simple zip file with both linux binaries and two (maybe more) batch scripts

Done in the last commit. I currently don't have access to a windows machine. Could you test it?

**Comment by vtereshkov** [comment]
Should I run `make windows`? Or `make package`? Or just unpack `tophat-win.zip`?

**Comment by marekmaskarinec** [comment]
You can either run `make win-package`, but the embedding on windows still isn't fixed, or just extract bin/tophat-win.zip

**Comment by vtereshkov** [comment]
Unsuccessful. `init.bat` creates a file, not a folder. `package.bat` creates two folders, `-windows` and `linux`, without any name prefixes.

![image](https://user-images.githubusercontent.com/52492460/115141715-838ad200-a046-11eb-8b08-52e4470f6324.png)

**Comment by vtereshkov** [comment]
That's what I have done to make it work:
`init.bat`
```
set /p Name=Enter name of the game: 
mkdir %Name%
copy /Y preset\*.* %Name%
```
`package.bat`
```
set /p Name=Target: 

mkdir %Name%-windows
mkdir %Name%-windows\tophat.dat
copy /Y %Name%\*.* %Name%-windows\tophat.dat
copy /Y bin\tophat-win.exe %Name%-windows

mkdir %Name%-linux
mkdir %Name%-linux\tophat.dat
copy /Y %Target%\*.* %Name%-linux\tophat.dat
copy /Y bin\tophat-linux %Name%-linux
```
Now I can run your `Hello World`.

**Comment by vtereshkov** [comment]
Perhaps it's better to rename the packaged binaries. So I've added
```
rename %Name%-windows\tophat-win.exe %Name%.exe
```
and
```
rename %Name%-linux\tophat-linux %Name%
```

**Comment by vtereshkov** [comment]
By the way, the space shooter now crashes on startup.

**Comment by marekmaskarinec** [comment]
Thanks for the help.

I will make a new issue for the crash.
