### ISSUE TITLE
Image rotation transforms also add the image cropping into the equation

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#100]

**Comment by marekmaskarinec** [comment]
Can you please explain this better?

**Comment by skejeton** [comment]
The rotation origin is dependent on image's cropping. So for example if the image is cropped at x=100,y=100,w=100,h=100. Then the origin will be offset by -100,-100, although it should be just 0,0. I think this is what's happening. Basically try rotating a cropped and uncropped image with and see the difference
