### ISSUE TITLE
Frame limiter doesn't work correctly on windows

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#104]
When I take the README code example and add time logging:
```
...  
for start := 0.0; window.cycle(cam) {
    stop := std.clock()
    printf(repr((stop - start) * 1000.0) + repr(th.delta) + '\n')
    start = stop
...
}
```
I get a 2x difference:
```
30.000000 16
31.000000 16
31.000000 16
31.000000 16
30.000000 16
16.000000 16
31.000000 16
31.000000 16
31.000000 16
31.000000 16
31.000000 16
31.000000 16
32.000000 16
31.000000 16
31.000000 16
31.000000 16
```
I suppose it may be a problem with `Sleep()` and timer resolution. It perhaps makes sense to get rid of `th.delta = 1000/fpsLimit` and recalulate `th.delta` using `std.clock()` rather than `fpsLimit`.

See also https://github.com/skejeton/save-game/issues/3#issuecomment-1250394856

CC @skejeton

**Comment by marekmaskarinec** [comment]
I will calculate the delta correctly, but this still doesn't fix the issue.

**Comment by marekmaskarinec** [comment]
This is definitely a problem with sleep.

> Sleep can cause the thread to sleep for longer than the timeout specified, it only guarantees that the thread will sleep for at least that length of time.

> From the [documentation](http://msdn.microsoft.com/en-us/library/windows/desktop/ms686298%28v=vs.85%29.aspx):

 > > After the sleep interval has passed, the thread is ready to run. If you specify 0 milliseconds, the thread will relinquish the remainder of its time slice but remain ready. Note that a ready thread is not guaranteed to run immediately. Consequently, the thread may not run until some time after the sleep interval elapses. For more information, see [Scheduling Priorities](http://msdn.microsoft.com/en-us/library/windows/desktop/ms685100%28v=vs.85%29.aspx).

**Comment by vtereshkov** [comment]
Yes, the limiter itself is still inaccurate, but at least it doesn't affect kinematics anymore. Thanks.

**Comment by skejeton** [comment]
ideally this can be solved if the rendering is strictly vsync, but that would mean the game input loop runs at vsync too, not so nice.
the only way I can think of right now, and that's probably the way it works most of the time, is to have a performance counter between the frame, and at the end of the frame, do a *precise* sleep for the time elapsed within that performance counter minus target framerate.

**Comment by skejeton** [comment]
@vtereshkov let me know what you think, it works okay for 60fps

**Comment by vtereshkov** [comment]
@skejeton Cross compiling fails:
```
src/bindings.c:14:10: fatal error: timeapi.h: No such file or directory
```

**Comment by skejeton** [comment]
@vtereshkov it's for timeGetTime function.. it may work if you comment it out, otherwise you may need some winmm headers or something like that

**Comment by skejeton** [comment]
to be fair i should use queryperformancecounter

**Comment by vtereshkov** [comment]
@skejeton After commenting out the `#include`, I got a working Windows executable. However, the new frame limiter is broken, since I have 350...400 FPS with it. If I rewind one commit back, I again have 35...50 FPS.

**Comment by marekmaskarinec** [comment]
@skejeton what's the current state of this issue?

**Comment by skejeton** [comment]
@marekmaskarinec it now uses a more precise sleeping routine, using performance counter. For now this is mostly fixed, the FPS is usually consistent with occasional ~2 FPS margin from my observations.
