### ISSUE TITLE
Fix subpixel shifts

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#109]
At the top you can see smushed text. That's because it's drawn at some subpixel position, either because of precision error or whatever else. I fixed it for fonts, but did a regression because it caused "wobbly font" issue, that's because I didn't account for screen scale. As a post-processing step, in vertex shader, at least for images, we need to floor the positions to fix this problem.   

![image](https://user-images.githubusercontent.com/27076041/197580903-2fc7cacd-f760-443c-b175-2cb5dafdf5a9.png)

**Comment by marekmaskarinec** [comment]
I would be happy to fix this, but it would be great to have a smaller test case. Could you make one.

**Comment by marekmaskarinec** [comment]
@skejeton do you mean something along the lines of
```
--- a/src/image.c
+++ b/src/image.c
@@ -1,3 +1,4 @@
+#include <math.h>
 #include <string.h>
 #include <stdint.h>
 
@@ -214,10 +215,8 @@ void th_blit_tex(th_image *img, th_quad q, uint32_t color) {
        thg->batch_tex = img->gltexture;
 
        for (uu i=0; i < 4; i++) {
-               q.v[i].x *= thg->scaling;
-               q.v[i].x += thg->offset.x;
-               q.v[i].y *= thg->scaling;
-               q.v[i].y += thg->offset.y;
+               q.v[i].x = trunc(q.v[i].x * thg->scaling + thg->offset.x);
+               q.v[i].y = trunc(q.v[i].y * thg->scaling + thg->offset.y);
        }
```

**Comment by skejeton** [comment]
@marekmaskarinec I think this may work yes!
