### ISSUE TITLE
Everything is completely broken on windows:

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#112]
(Happened after merge into msbuild branch)
![image](https://user-images.githubusercontent.com/27076041/200185890-8ec40422-e484-4fb2-ac5e-aec4f7287bb7.png)

**Comment by skejeton** [comment]
in particular it appears images are affected, but probably something's messed up with the render commands?

**Comment by skejeton** [comment]
really wack, the only commit that could've done something like that is the image smearing fix, but idk

**Comment by skejeton** [comment]
(p.s. i'll try figuring out myself tomorrow but if you have any ideas please lmk :P!

**Comment by marekmaskarinec** [comment]
> really wack, the only commit that could've done something like that is the image smearing fix, but idk

I think so too.

Is it broken in the main branch too? You can download it here: https://mrms.cz/dl/up/tophat.exe.

Btw how do I build `msbuild` tophat on windows? Best without needing to install visual studio.

**Comment by skejeton** [comment]
@marekmaskarinec sadly the script requires to install visual studio build tools

**Comment by skejeton** [comment]
whoops closed it accidentally. but you can also do it without visual studio build tools, you'll need to tweak the cmake script though

**Comment by skejeton** [comment]
when i use this executable it says invalid block size on the game, maybe the umka version is old?

**Comment by skejeton** [comment]
![image](https://user-images.githubusercontent.com/27076041/200187270-bc410ed6-8737-49ea-91c6-4e4bb53069d6.png)
running new dialogs

**Comment by vtereshkov** [comment]
> when i use this executable it says invalid block size on the game, maybe the umka version is old?

I reported this problem just after the tophat 0.8 release:

https://discord.com/channels/846663478873030666/846663478873030672/1033845167565844551

**Comment by marekmaskarinec** [comment]
Maybe this is some kind of cross compilation bug.

**Comment by vtereshkov** [comment]
@skejeton I can compile a fresh Windows build from the `main` branch, but am not sure it will help you much.

**Comment by marekmaskarinec** [comment]
The umka version (atleast on the main version) seems to be really old. I will try updating it.

**Comment by vtereshkov** [comment]
@marekmaskarinec For me it works fine. However, I'm a little bit confused. In principle, we have four ways to build tophat:
* Linux
* Windows (cross compiling from Linux)
* Windows (MinGW)
* Windows (Visual Studio)

What option to use to reproduce the original issue? I successfully tested Save Game with option 2 (both `main` and `msbuild` branches), except that I had to add `glad.c` to `src/Makefile`.

**Comment by skejeton** [comment]
> @marekmaskarinec For me it works fine. However, I'm a little bit confused. In principle, we have four ways to build tophat:
> 
> * Linux
> * Windows (cross compiling from Linux)
> * Windows (MinGW)
> * Windows (Visual Studio)
> 
> What option to use to reproduce the original issue? I successfully tested Save Game with option 2 (both `main` and `msbuild` branches), except that I had to add `glad.c` to `src/Makefile`.

Windows Visual studio

**Comment by skejeton** [comment]
I can confirm everything was fixed after submodule update 🎉 ✨ 
![image](https://user-images.githubusercontent.com/27076041/200214275-36c2d0bc-9062-4604-b17c-8d5c3788f372.png)
