### ISSUE TITLE
CI/Linux Build fix for msbuild branch

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#113]
Right now, the CI fails for Linux on msbuild branch because I replaced chew.h with GLAD. Needs to be fixed.

CC @marekmaskarinec

**Comment by marekmaskarinec** [comment]
I fixed the glad errors, but the CI is still failing because of `timeapi.h`. It works fine on my machine.

**Comment by skejeton** [comment]
> I fixed the glad errors, but the CI is still failing because of `timeapi.h`. It works fine on my machine.

I'll fix it by using different api

**Comment by marekmaskarinec** [comment]
input.getMouseDelta() gets
