### ISSUE TITLE
Inconsistency between windows and Linux w.r.t. mouse movements

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#115]
On Linux, at least i3wm, when you press on the window and move it around inside, you can move it outside and it would count in Tophat. Tophat on Windows stops immediately after you leave the window area. What is the preferred option?

**Comment by marekmaskarinec** [comment]
What do you mean by this?

**Comment by skejeton** [comment]
This was poorly explained and no longer an issue since we switched to Sokol. The problem was that on windows if you pressed the left mouse button on the window and then dragged it away from the window, the mouse tracking would stop. On Linux the mouse tracking continued. This could be demonstrated by moving a window titlebar - on Linux it would move outside the window because the cursor is still tracked, but on Windows it'd stop on the last frame the cursor was in the window. 

The behaviour now is consistent, and I think the best one - to continue tracking outside the window after press. I'm closing this issue, but re open if you have any objections.
