### ISSUE TITLE
Ability to go fullscreen

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#116]
These shortcuts are the most common shortcuts in games, and I really like "just playing" in fullscreen mode. Previously on Linux, i3wm I could enable fullscreen mode by using the WM hotkey, but it's not consistent across platforms. On Windows for instance, it's not possible to make it fullscreen. It may also be not possible on some Linux WM's.

Some considerations:

* The checks for Alt+Enter and F11 should run after the user loop, because they might want to block those events for their own behaviour, although it's not a critical break.
* May not be relevant for wasm build, because the events are likely to get sunk by the browser for its own use.

I can work on Windows side of that.

**Comment by marekmaskarinec** [comment]
I think we should just add something like `window.setFullscreen(bool)` and let user implement those key binds themselves.

**Comment by skejeton** [comment]
I agree we should add `setFullscreen` regardless. I'll do my part on Windows right now

**Comment by marekmaskarinec** [comment]
I've managed to make a fullscreen implementation for X. The only problem is that the KDE bar still appears above the window. I guess it will be similar with other DEs (KDE is the only one I have installed). Works completely fine with dwm though. I will investigate more.

**Comment by marekmaskarinec** [comment]
Have you ever done this @skejeton? I've tried multiple solutions and I can't find any that work reliably.

**Comment by skejeton** [comment]
@marekmaskarinec I've never implemented it for X, but I'm sure you can look at how sokol or glfw does it. On windows the way to do it is to resize the window to fit the entire screen, make it the topmost window, disable decorations (titlebar/buttons) and if neccessary resize the screen.
