### ISSUE TITLE
Consistent names between bindings

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#117]
Currently there's several ways the binding functions are named:

1) Starting with c: `cgetmouse`, `cispressed`...
2) Starting with module name: `imggetdims`, `imgcrop`...
3) Ending with module name: `loadimg`, `flipvimg`...
4) No convention at all: `drawText` `drawLine`...
5) Full armour namespacing: `umth_hsv2rgb_uint32`, `umth_rgb_uint32`, `umth_sound_copy`, `umth_window_end_scissor`...

There should be some consistency, my personal favourite is 5.

**Comment by marekmaskarinec** [comment]
5 is also my favorite. All bindings should be rewritten, but it will be a lot of work.
