### ISSUE TITLE
Space shooter example crashes on startup

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#12]
https://github.com/marekmaskarinec/tophat/issues/10#issuecomment-821971293

**Comment by marekmaskarinec** [comment]
It runs perfectly fine for me. Does it have some kind of output? I added a new umka library, so make sure, you don't have old version of umkalibs.h.

**Comment by vtereshkov** [comment]
This is actually not a new problem. It's again about packaging. `copy` doesn't copy folders recursively. I have to use `xcopy` instead:
```
set /p Name=Target: 

mkdir %Name%-windows
mkdir %Name%-windows\tophat.dat
xcopy /Y /s /e %Name% %Name%-windows\tophat.dat
copy /Y bin\tophat-win.exe %Name%-windows
rename %Name%-windows\tophat-win.exe %Name%.exe

mkdir %Name%-linux
mkdir %Name%-linux\tophat.dat
xcopy /Y /s /e %Name% %Name%-linux\tophat.dat
copy /Y bin\tophat-linux %Name%-linux
rename %Name%-linux\tophat-linux %Name%
```
Now the space shooter seems to be working.

**Comment by marekmaskarinec** [comment]
Fixed. Btw, you can run games without packaging them using `run.bat` in the game directory.

**Comment by vtereshkov** [comment]
Looks like you fixed it in `cmd`, but not in the archives.

**Comment by marekmaskarinec** [comment]
It is fixed in the archive.

**Comment by vtereshkov** [comment]
Also the `/s` and `/e` keys are missing in `xcopy`. So it doesn't work.

**Comment by marekmaskarinec** [comment]
Sorry, I will fix it later today. Windows is hard.

**Comment by marekmaskarinec** [comment]
Try it now.

**Comment by vtereshkov** [comment]
OK
