### ISSUE TITLE
Tophat screenshot for Projects section

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#14]
Could you please upload a good screenshot or another promotional picture (preferably 640 x 480 PNG) for the Projects section of the Umka page on GitHub?

**Comment by marekmaskarinec** [comment]
Yes. I can make some screenshots for you. What exactly do you mean by "Projects section of the Umka page on GitHub"? Is it still being worked on, or am I just blind?

**Comment by marekmaskarinec** [comment]
Ok. Now I see. I will make some screenshots tomorrow.

**Comment by marekmaskarinec** [comment]
Here you go, although you already have better one.

![2021-05-01-103003_694x1011_scrot](https://user-images.githubusercontent.com/42782325/116776966-e713f700-aa6b-11eb-85db-b956efc2eb37.png)

**Comment by vtereshkov** [comment]
OK, I think I'll keep using what I already have.
