### ISSUE TITLE
ui.TextBox: New characters are entered at the end of line rather than at the cursor position

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#141]
![image](https://github.com/marekmaskarinec/tophat/assets/52492460/7fe830d9-bea5-4830-9762-63e7b8738818)
![image](https://github.com/marekmaskarinec/tophat/assets/52492460/b896c1de-21f2-42ec-86b4-9e3cf798014e)

**Comment by skejeton** [comment]
confirmed

**Comment by skejeton** [comment]
fixed

**Comment by vtereshkov** [comment]
Verified and closed.
