### ISSUE TITLE
ui.TextBox: pressing ctrl+backspace will add a weird character.

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#144]
![image](https://github.com/marekmaskarinec/tophat/assets/27076041/ac13aca5-af6e-4606-ade6-102fb4485dc6)

This character is DEL, we can see that in the rail game:

![image](https://github.com/marekmaskarinec/tophat/assets/27076041/3f48b1c4-a4b0-4bac-a7a6-2398329c2dec)

**Comment by marekmaskarinec** [comment]
We will rebind this to remove a word anyways in the future.

**Comment by marekmaskarinec** [comment]
This doesn't seem to happen on my linux machine.

**Comment by skejeton** [comment]
I think it's because this varies wildly in Sokol for different platforms.

**Comment by marekmaskarinec** [comment]
I think a good fix would be to disallow entering control characters.
