### ISSUE TITLE
Web builds: `STACK_SIZE` option is not supported by older Emscripten versions

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#147]
The `STACK_SIZE` option is quite new and is not supported by my Emscripten (I have had to downgrade it to 3.1.10 because both 3.1.47 and 3.1.51 were failing):
```
emcc: error: Attempt to set a non-existent setting: 'STACK_SIZE'
```
We can use `TOTAL_STACK` instead: 

https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3125---110822

**Comment by marekmaskarinec** [comment]
The problem is each of us has a different version of emscripten. For example I have 3.1.39. Maybe the most sane solution would be to download emscripten on demand ourselves.

**Comment by vtereshkov** [comment]
@marekmaskarinec Can you build and run both the playground and examples with 3.1.39? I have never tested it. Perhaps we can close this issue by just choosing the "recommended" Emscripten version for us all.

**Comment by marekmaskarinec** [comment]
I'm having even more issues with my version.

**Comment by skejeton** [comment]
Emscripten changes its CLI so much, and they've been improving, so honestly I think adopting new features is fine.

**Comment by skejeton** [comment]
@vtereshkov Let's just use the latest stable? As I said Emscripten is improved a lot over time. To compile with always the latest version you can use EMSDK, available for Windows and Linux: https://github.com/emscripten-core/emsdk
It's pretty easy to use and easy to update your Emscripten version.

**Comment by marekmaskarinec** [comment]
I agree with this. Let's aim for the `latest` version. This is also the one used in our emscripten CI.

**Comment by vtereshkov** [comment]
Can you confirm there are no problems with the latest Emscripten?

**Comment by vtereshkov** [comment]
I tested the latest Emscripten 3.1.56 with the playground and the Flappy example. Seems to be working, except #172 and #173 (which are probably not related to Emscripten).
