### ISSUE TITLE
Umka memory leaks are not reported after `exit()`

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#149]
If I print a report after an `exit(0)`, we'll get too many false positives even in simplest programs -- just because the VM has not exited all the `{...}` scopes properly before `exit(0)`.

If I don't print a report after an `exit(0)` (which is now the case), we'll almost never see any leak reports at all, except when quitting with the 🗙 button.

Our old `window.quit()` wasn't actually a quit function, but rather a notification deferred until the end of the current frame. For the memory leak detection it was much better than a hard exit.

I think, the final decision depends on whether you were annoyed by the fact that `window.quit()` didn't act immediately, that is, didn't quit the function it was called from.

If you were, we can use `exit(0)` instead and even ignore the leak detector problem. 

If you weren't, `window.quit()` may be better.

For me, `exit()` is more about a "slightly abnormal" termination, but I don't insist on this interpretation.

**Comment by marekmaskarinec** [comment]
I think that a better solution than keeping two different `exit` functions, which could be very confusing, we could pass some kind of flag to the `onFrame` method, which if set, returns from the game.

```
window.onFrame.register({
  // exit from the game
  ^bool(args[0]) = true
})
```

**Comment by marekmaskarinec** [comment]
That is true, but as I said, I'm not sure it's a good idea to have two different exit functions.

**Comment by vtereshkov** [comment]
@marekmaskarinec I see. But for me, it could be enough to have a more appropriate name for `window.quit()`, such as `window.requestQuit()`, `window.needQuit()` or `window.notifyQuit()`. And `exit()` for a "slightly abnormal" termination, as I said.

**Comment by marekmaskarinec** [comment]
That could work

**Comment by skejeton** [comment]
Added `requestExit`. If this covers the issue please close it.

**Comment by vtereshkov** [comment]
Fix confirmed. In the rail game, I get a memory leak report after clicking "Exit":
```
if gui.qbutton("Exit") {
	window.requestExit()
}
```
