### ISSUE TITLE
Compiling for windows

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#15]
There are problems with linking opengl probably.

**Comment by marekmaskarinec** [comment]
> Updating submodules in make deps resets the Umka version to an outdated one, even if I copy a folder with a newer version manually. This revives the old method import problem, vtereshkov/umka-lang#61.
Thanks for pointing out. Fixed in last commit.
> Invoking umka cmd/embedder.um fails. I have had to replace it with lib/umka/build/umka cmd/embedder.um.
Good idea. Now user isn't required to have umka installed.
> The light.um module is not embedded.
Lights are still very experimental and I don't know, if I will even include them (they actually aren't lights at all).

**Comment by marekmaskarinec** [comment]
Fixed.

**Comment by vtereshkov** [comment]
Building under Linux is almost OK, except that I cannot run `make package` because I don't have a Windows cross-compiler.

Building under Windows is still a big problem for a number of reasons:
* The `echo` command syntax is different
* `curl` is not a standard Windows utility

The pre-built Windows package works well, except that it always prints warnings like
```
Warning: Can't find "glglNamedBufferData"
Warning: Can't find "glglEnableVertexArrayAttrib"
Warning: Can't find "glglDisableVertexArrayAttrib"
Warning: Can't find "glglNamedBufferSubData"
Warning: Can't find "glglDebugMessageCallback"
Warning: Can't find "glglDebugMessageControl"
Warning: Can't find "glglNamedRenderbufferStorageMultisample"
Warning: Can't find "glglBlitNamedFramebuffer"
Warning: Can't find "glglCheckNamedFramebufferStatus"
Warning: Can't find "glglMapNamedBuffer"
```

**Comment by marekmaskarinec** [comment]
> Building under Linux is almost OK, except that I cannot run make package because I don't have a Windows cross-compiler.

I will check if user has mingw installed and put a warning, but packaging without window binaries shouldn't be done.

> The echo command syntax is different
•  curl is not a standard Windows utility

Is the problem with echo the `\n`? If yes, I can easily fix that. As for curl, that might be a bit of a problem.

> The pre-built Windows package works well, except that it always prints warnings like

I noticed this too, but it was only one function. This looks like a driver issue to me, but I'm not sure. I will look into it.

**Comment by vtereshkov** [comment]
> Is the problem with echo the \n?

Not only `\n`, but also quotes `" "`. Windows `echo` does not like them.
