### ISSUE TITLE
std.exitif exits without a message on windows.

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#159]
stdout is disabled, so it needs to be an infobox.

**Comment by marekmaskarinec** [comment]
Not sure how to fix this. Make a custom `th.exitif`? Ship a patched version of `std.um`?

**Comment by vtereshkov** [comment]
Does it happen in a custom tophat build? Otherwise, why is the `stdout` disabled?

**Comment by marekmaskarinec** [comment]
Normally, errors in tophat are reported through system dialogs so they are visible to users not running from terminal, but that's not the case for exitif. I think that's what ske means.

**Comment by vtereshkov** [comment]
Can we close the issue?

```
  f, err := std.fopen("test.test", "rb")
  std.exitif(err)
```

![image](https://github.com/marekmaskarinec/tophat/assets/52492460/0abb0606-f900-44f8-a22f-8b52937c237d)

**Comment by skejeton** [comment]
Yep
