### ISSUE TITLE
Incorrect blending when using a render target.

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#161]
Drawing a texture with transparency will overwrite the color instead of blending it.

**Comment by marekmaskarinec** [comment]
There doesn't seem to be any obvious mistake, this is very suspicious. Any ideas @skejeton?

**Comment by marekmaskarinec** [comment]
The blending properties seem to be the same as in the canvas pipeline.

**Comment by skejeton** [comment]
I think I see what you mean: 
![image](https://github.com/marekmaskarinec/tophat/assets/27076041/58e4586e-c792-4645-a6ab-6160ee294b59)
Here I added transparency to both placeholder and render target.

**Comment by skejeton** [comment]
I think I might know why. The background in the render target is 0x00000000, e.g. completely transparent, but also black. It'd explain why it blends in this gray color.

**Comment by marekmaskarinec** [comment]
I mean this (the text is rendered over the sign in a render target mode):

![image](https://github.com/marekmaskarinec/tophat/assets/42782325/cb3793a6-b6bc-4df6-9f5a-8dd95137ff6d)

**Comment by skejeton** [comment]
Hmm, how do you draw the entity frame?
```
        e.tex.img.draw({
                s: { 1, 1 }
        })
```
I assume this, but is e.tex.img initialized to be the frame before that?

**Comment by skejeton** [comment]
@marekmaskarinec I found one prominent issue is that framebuffers are inherently pre-multiplied in the end, inconsistent with the straight alpha blending mode we do.

**Comment by skejeton** [comment]
@marekmaskarinec I added pre-multiplied alpha to render targets, test it out!

**Comment by skejeton** [comment]
@marekmaskarinec I think I figured out the problem, in the most recent commit you accidentally used `pass_action` instead of `offscreen_pass_action`.

**Comment by marekmaskarinec** [comment]
Fix confirmed.
