### ISSUE TITLE
Playground: Cannot select or run "Hello world" after startup

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#162]
In order to run "Hello world", I have to select some other example and then switch back to "Hello world".

Otherwise, I get an error:

![image](https://github.com/marekmaskarinec/tophat/assets/52492460/e98b45cb-f20f-41b4-9b03-b24168133647)

**Comment by marekmaskarinec** [comment]
This is just a result of a different issue. The whole init procedure of the playground is rather finicky. Maybe a rewrite would be good.

**Comment by vtereshkov** [comment]
A simpler solution would be to start with an "empty" menu item that showed the tophat splash screen (like in my screenshot), then I'd select the "Hello world" example manually.

**Comment by marekmaskarinec** [comment]
I decided to go with your workaround for now.
