### ISSUE TITLE
Update mmdoc

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#168]
https://github.com/marekmaskarinec/tophat/actions/runs/8281813607/job/22661171777#step:4:136

**Comment by vtereshkov** [comment]
More generally, we need to switch tophat to the updated Umka standard library:
* Most file I/O functions now return `std.Err`
* There is `std.freadall()`

**Comment by skejeton** [comment]
I fixed buildhelper and the CI should pass, but mmdoc has to be done from Marek's side.

**Comment by vtereshkov** [comment]
There was also a custom (and ugly) `readall()` in `misc.um`.

**Comment by skejeton** [comment]
Noted. I think I just found a bug in freadall, I'm going to post it in the Umka repository.

**Comment by marekmaskarinec** [comment]
> There was also a custom (and ugly) `readall()` in `misc.um`.

I remember this ancient implementation from the times when there was no `ftell`.
