### ISSUE TITLE
Docs: Broken link

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#169]
The link at the end of this page is broken. https://docs.tophat2d.dev/tut/spritesheet.html

Reported by https://www.reddit.com/user/Inconstant_Moo/

**Comment by marekmaskarinec** [comment]
Links in other tutorials are also broken.

**Comment by marekmaskarinec** [comment]
The link is removed for now, until I figure out what to do with these tutorials.
