### ISSUE TITLE
Properly exiting on window close

### ISSUE THREAD

**Issue by youssefsahli** [marekmaskarinec/tophat#17]
How to trigger it: run, in the examples directory, the level editor: tophat run
close the window, and check the output: 
` X connection to :0 broken (explicit kill or server shutdown).
Warning: Memory leak at 0x7f9d64cf2010 (6 refs)
Warning: Memory leak at 0x561a03d02410 (17 refs)
Warning: Memory leak at 0x561a03e022a0 (1 refs)
X connection to :0 broken (explicit kill or server shutdown).

Version: cloned git 11 march 2021.

**Comment by vtereshkov** [comment]
@marekmaskarinec I carried out an almost successful experiment, though it was Windows-specific. I rewrote `CNFGTearDown()` in the following manner:
```
extern char killed;

void CNFGTearDown()
{
	PostQuitMessage(0);
#ifdef CNFGOGL
	//exit(0);
#endif
	killed = 1;
}
```
Then I added a function to check the `killed` flag from Umka:
```
void umkilled(UmkaStackSlot *p, UmkaStackSlot *r) {
	r->intVal = killed;
}
```
and added the exit condition to the main game loop:
```
	for !ckilled() {
		tophat.cycle(&global.w, &global.h, global.bg_color, global.cam)
		// ...
	}
```
Now I have an almost correct exit procedure except for some problems with `th_audio_deinit()`.

**Comment by charleslvalve** [comment]
Could you instead use `HandleDestroy()`? which should be called back on a destroy event?

**Comment by cnlohr** [comment]
Could you instead use HandleDestroy()? which should be called back on a destroy event?

**Comment by vtereshkov** [comment]
@cnlohr The main problem is with `exit(0)` called from `CNFGTearDown()`. This call means that the `main()` function in `main.um` (executed from `umkaRun(umka)`) does not terminate correctly and does not run garbage collection for Umka's global objects.

**Comment by marekmaskarinec** [comment]
> Could you instead use HandleDestroy()? which should be called back on a destroy event?
I already tried this, but (at least on with X driver), it doesn't have time to finish the loop before `HandleDestroy` is called and the program exits.

**Comment by cnlohr** [comment]
It sounds like Ilya's suggestion in-channel, to make `CNFGHandleInput()` return false upon close request is the direction we're headed right now. I don't know how well that will work on all platforms but we can see.

**Comment by marekmaskarinec** [comment]
I made a pr implementing ShouldClose on windows a long time ago. The linux pr (not mine) still isn't merged because it does some other changes (probably a mistake). The author didn't fix them yet. I asked him about it on friday and he said he would fix it on this monday, but he hasn't. I'm considering making the fixed pr myself.

**Comment by marekmaskarinec** [comment]
Tophat now exits cleanly on window close.
