### ISSUE TITLE
lights: Proper color blending

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#19]
Lights don't blend correctly.
![Peek 2021-08-11 20-47](https://user-images.githubusercontent.com/42782325/129088566-e0cc94ed-9779-4f67-ab98-e563b75e3b26.gif)

This should be solved using a color blending function, that takes into consideration alpha of both color. The closer alpha is to alpha of lightmasks color, the less influence it has.

**Comment by iotasieve** [comment]
blending of lights is usually solved via addition, try adding colors, you'll see metaball-ish behavior you need
