### ISSUE TITLE
Projectiles bug in Space shooter

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#22]
I have tried to build the latest `tophat`, rename it to `space-shooter`, copy it manually to the `examples/space-shooter` folder, rename `umka` to `tophat` and copy it to the same folder, then run `./space-shooter run`.

The game starts normally, but projectiles are either not shown at all, or look like yellow strips. When I press the fire button, the enemy ships in all columns are destroyed simultaneously.

The issue is the same on Linux and Windows (cross-compiled with `make cross`).
 
![image](https://user-images.githubusercontent.com/52492460/132403767-d774145e-443d-4f16-a3e9-e094dc8acfd4.png)

**Comment by marekmaskarinec** [comment]
This should be fixed now. It was a really stupid bug.

By the way, you don't need to add the `run` flag. The tophat binary itself searches for `main.um`, `tophat.dat/main.um`. The cli wrapper on the other hand requires it. You also shouldn't need to copy the libraries as they are supposed to be embedded. This was however broken in the makefile pr, but I fixed it while fixing this bug.
