### ISSUE TITLE
Emitter deletes itself instantly

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#26]
https://github.com/marekmaskarinec/tophat/commit/6e2a73e3cbce3571abcbf7d0c1c28982222621a7#r57447149

**Comment by vtereshkov** [comment]
@marekmaskarinec I see this effect on both Windows and Linux. Indeed, if `th.time` when calling `draw()` is still less than `th.time + std.rand() % 200` for all particles when creating the emitter (which is quite possible, though not necessary), the emitter will be immediately removed. When I replace `th.time + std.rand() % 200` with `th.time + std.rand() % 200 - 200` (i. e., all particles have already been randomly emitted by the time of emitter creation), the problem disappears.

**Comment by marekmaskarinec** [comment]
That seems to be a problem although it's weird it works perfectly for me. It should be easily fixable by moving `p->active = true;` above the condition in particle draw.

**Comment by marekmaskarinec** [comment]
This seems to be the problem, although I find it weird that it doesn't happen on my pc. I know of an easy fix and I will push it later today.

**Comment by marekmaskarinec** [comment]
I was able to recreate this after I set `_th_particle`'s alignment to 1. Fixed in the last commit.
