### ISSUE TITLE
Windows build is not working

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#29]
When running Space Shooter, I get the folloowing error message:
```
←[1m←[31merror: ←[0mhud.um (35, 22): Incompatible types Vf2 and Transform
```

**Comment by marekmaskarinec** [comment]
Is this the build from release? Turns out it is old. It works with the new one (in wine) and I updated the release.

**Comment by vtereshkov** [comment]
@marekmaskarinec Yes, it's from `tophat-win.zip`. When I build it from source with `make cross`, everything is OK.
