### ISSUE TITLE
Crash on exit when accessing Umka-managed memory from C

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#31]
The `auarr` array is owned and managed by Umka, so it is dangerous to store a reference to it (i. e., `sounds`) in C, as the memory can be freed at any time without notifying the C code. Instead, its constents should be copied into a C array. 

For example:
```
void umauarr(UmkaStackSlot *p, UmkaStackSlot *r) {
	uu count = p[0].intVal;
	th_sound **auarr = (th_sound **)p[1].ptrVal;

	sound_count = count;
	
	if (sounds)
		free(sounds);
	
	sounds = malloc(sound_count * sizeof(th_sound *));
	memcpy(sounds, auarr, sound_count * sizeof(th_sound *));	
}
...
void th_audio_deinit() {
	ma_device_uninit(&audev);

	if (!sounds)
		return;
		
	for (int i=sound_count - 1; i >= 0; i--) {
		ma_decoder_uninit(&sounds[i]->decoder);

		free(sounds[i]);
	}
	
	free(sounds);
	sounds = NULL;
}
```

**Comment by vtereshkov** [comment]
> I think I already came across this issue as setSounds is called every time a sound is loaded.

The problem is that you first return from `main()` in Umka (which means that all global variables are deallocated) and then try to deinitialize your sounds. Even though you still have the sounds themselves (since they have been allocated in C), they are no longer accessible, because the "table of contents", i. e. `auarr` or `sounds`, is lost.

**Comment by marekmaskarinec** [comment]
Oh. This makes it much more clear. I thought global variables would be free'd on `umkaFree` call.

**Comment by vtereshkov** [comment]
It's a subtle point. All heap-allocated variables in Umka are freed by the garbage collector, which is a part of the Umka virtual machine and cannot be run after the machine halts upon returning from `main()`. On the other hand, all "static" variables are freed by `umkaFree()`. If `umkaFree()` discovers any heap-allocated variables, it prints the `Memory leak` warning and deallocates them - this is considered either a garbage collection bug, or a symptom of terminating the whole program before returning from `main()`. 

For example, if you declare a global dynamic array, you actually have a "static" control record, which contains the data pointer, data size etc., and a heap-allocated data block. The former is freed by `umkaFree()`, the latter upon returning from `main()`. 

The variables considered as "static" in Umka are actually also allocated in heap under the hood. But this is done by C and is not tracked by the garbage collector.
