### ISSUE TITLE
Crash on exit when calling die() twice

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#32]
It seems that sometimes `die()` is called twice - first from `main()`, then from `HandleDestroy()`. One needs a protection against this.

For example:
```
bool died = false;

void die() {
	if (died)
		return;
	
	th_audio_deinit();
	if (destroyfunc) {
		umkaCall(umka, destroyfunc, 0, NULL, NULL);
	}

	umkaFree(umka);
	died = true;
}

void HandleDestroy() {
	die();
	exit(0);         //  <-- I've added this, but it needs further invesigation
}

```

**Comment by vtereshkov** [comment]
@marekmaskarinec Still segfaulting for the same reason, i. e., no `exit(0)` in `HandleDestroy()`. The sequence of events is as follows:
* Returning from Umka `main()`
* Returning from C `main()`
* Calling `HandleDestroy()` (from another thread?)
* Returning from `HandleDestroy()`
* Segmentation fault

**Comment by vtereshkov** [comment]
@marekmaskarinec On the other hand, it seems that rawdraw performs important actions _after_ calling `HandleDestroy()`. So we have to be careful.

**Comment by vtereshkov** [comment]
@marekmaskarinec I have just discovered that my current problem is not with `die()` but with `XCloseDisplay( CNFGDisplay )`. This is where the segmentation fault occurs. So it's a question to the rawdraw author, I think.

**Comment by marekmaskarinec** [comment]
`die` is now called only once - at the end of main.
