### ISSUE TITLE
Limit rate of fire in space shooter?

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#33]
Now the most efficient strategy in the space shooter is the most stupid one: hold `A` or `D` and hit space bar as frequently as you can. To encourage using smarter strategies, we can limit the rate of fire. For example:
```
	if input.isJustPressed(input.KEY_SPACE) {
		if delay > 300 {
			delay = 0

			sound.shoot.play()
			b := bulletPrefab
			b.t.p = th.Vf2{e.t.p.x + 1, e.t.p.y - bulletPrefab.r.h}

			bullets = append(bullets, b)
			b.t.p.x += 3
			bullets = append(bullets, b)
		}
	}

	delay += th.delta
```

**Comment by marekmaskarinec** [comment]
I can implement this, although I think I should try making the space shooter more readable and small than fun to play and balanced.
