### ISSUE TITLE
A* pathfinding

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#37]
To navigate in a maze, game characters may need to use some pathfinding algorithm like https://en.wikipedia.org/wiki/A*_search_algorithm.

**Comment by marekmaskarinec** [comment]
I want to add this one day, but for now it's low priority.

**Comment by marekmaskarinec** [comment]
I think it would be better if the A* was able to take any kind of graph as an input - not only operate on tilemaps. Tilemaps would obviously have a functions for generating said graph.
