### ISSUE TITLE
Using ptrVal as an alias for intVal is no longer allowed in Umka

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#39]
As Umka now defines `ptrVal` as `void *` instead of `int64_t`, it reveals several bugs (or at least typos) in tophat:

https://github.com/marekmaskarinec/tophat/blob/5931dc958b7a794ab31bbdbe174cb94ac340248e/src/bindings.c#L270
https://github.com/marekmaskarinec/tophat/blob/5931dc958b7a794ab31bbdbe174cb94ac340248e/src/bindings.c#L623

**Comment by marekmaskarinec** [comment]
Should be fixed.
