### ISSUE TITLE
Error using pass-by-value semantics?

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#4]
https://github.com/marekmaskarinec/tophat/blob/7741a5aec5a932dad2b4a845765c3db72f024152/src/bindings.c#L48

If you would like to pass by value a structure that is larger than the Umka stack slot size (8 bytes), you have to calculate the actual number of slots occupied by the structure and update the slot indices accordingly. For example, if you have an Umka function signature 
```
fn (scene: ^entity, e: entity, count: int)
```
and the structure `e` is _packed with alignment 1_, the stack slot layout would be like
```
0:  count
1:  e.p
2:  e.image
3:  e.color, e.id
4:  scene
```
If `e` is not packed, the layout will depend on the default alignment, which is hard to predict. My opinion is that to write more reliable and portable code, it's better to have all structure fields multiple of 64 bits. 

By the way, the default integer type (`int`) in Umka is 64-bit, which is equivalent to `int64_t` in C.

**Comment by marekmaskarinec** [comment]
Wouldn't  it be easier to pass a pointer, since that would negate all the size problems.

I also want to thank for all the help you are with this.
