### ISSUE TITLE
Tophat fails to display particles

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#40]
No particles are displayed in the space shooter example with the recent version of tophat, while the Nov 26 version (with the fixes for #39 applied manually) works well.

**Comment by marekmaskarinec** [comment]
Displays the particles for me.

**Comment by vtereshkov** [comment]
@marekmaskarinec Umka is now using naturally aligned structures. This allows me to run Umka on SPARC and other machines that are intolerant to misaligned addressing (see also https://github.com/vtereshkov/umka-lang/issues/19#issuecomment-997221260). So you have to remove `#pragma push(pack, 1)` and `#pragma pop(pack)`.

**Comment by marekmaskarinec** [comment]
Should be fixed.

**Comment by vtereshkov** [comment]
Now working.
