### ISSUE TITLE
Embedding not working in Makefile

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#41]
When I remove `staembed.c`, run `make deepclean` and `make all`, I get the error `/lib/umka/build/umka: not found`. Then I run `make umka`, `make all` and get a linker error because `staembed.c` is empty. It seems that the `$(EM_TARGET)` task is not run at all.

If I keep `staembed.c` as is, `make all` completes successfully.

**Comment by marekmaskarinec** [comment]
I fixed the embed rule being run before umka is built, so now tophat should build from scratch. `staembed.c` is supposed to be kept.

> It seems that the $(EM_TARGET) task is not run at all.

It only runs if `$(EM_TARGET)` doesn't exist or any of the umka modules have changed.
