### ISSUE TITLE
Invalid path prefix on Windows makes conv_path() fail

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#43]
On Windows, relative paths don't start with `./` and absolute paths don't start with `/`. The current logic in `conv_path()` constructs invalid paths like `./C:\Users`.

**Comment by marekmaskarinec** [comment]
This should be fixed now. Instead of `./`, nothing is used. If you want to keep the path as is, you have to prepend it with `raw://`.
