### ISSUE TITLE
Text rendering is an expensive task

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#53]
Text rendering is very expensive and makes tophat's CPU usage grow a lot. On my CPU, the space shooter takes around 8%, but tests/uit.um takes around 20%.

A possible cause is the use of codepoints instead of glyph indices.
https://github.com/nothings/stb/blob/af1a5bc352164740c1cc1354942b1c6b72eacb8a/stb_truetype.h#L241
I will try storing the glygh index in the font cache and see how that goes.

**Comment by marekmaskarinec** [comment]
This didn't help at all.

The next culprit could be that I always try to cache the string when drawing, which means its decoded and every rune is hashed.

**Comment by skejeton** [comment]
first things first you can try to optimize it by putting images into an atlas instead of individual image. of course you need to identify the bottleneck first instead

**Comment by marekmaskarinec** [comment]
I will try that since the profiler tells me most time is spent in `glDrawArrays`.

**Comment by skejeton** [comment]
The CPU usage reduced drastically for me as we moved on to the newer atlas based text renderer, I think this issue can be considered closed.
