### ISSUE TITLE
Errors in tophat modules report the module being alongside

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#54]
```
~/p/tophat | ./tophat main tests/scissorst.um
error: tests/window.um (1, 2): Declaration expected but / found
```
(simulated error)
The `scissorst.um` file imports erroneous `window.um`. This wouldn't be an issue if the core files don't have errors, but this could be an issue if they have runtime errors because of user input.

**Comment by marekmaskarinec** [comment]
I'm not sure what exactly you mean by this. `scissorst.um` works fine for me. Are you sure this isn't a problem with your fork?

**Comment by marekmaskarinec** [comment]
Or did you meant that it shows the `tests/` directory? If thats the problem, then I can't affect that. Make an umka issue instead.

**Comment by marekmaskarinec** [comment]
I will update the umka submodule version after I sort out the shader issue.

**Comment by vtereshkov** [comment]
In the latest version of Umka, the following rules apply:
* All modules use their regularized (or 'cleaned') absolute paths as the unique IDs
* When registering an embedded module, its absolute path is the current folder (i. e., the folder Umka is run from) plus the path specified as a part of the fake file name in `umkaAddModule()`
* When importing a real module, its absolute path is the current module's folder (i. e., the folder containing the current module) plus the path specified in the `import` clause
* When importing an embedded module, its absolute path is the current folder (i. e., the folder Umka is run from) plus the path specified in the `import` clause

See also https://github.com/vtereshkov/umka-lang/issues/145

**Comment by marekmaskarinec** [comment]
Can this be closed now?

**Comment by vtereshkov** [comment]
@marekmaskarinec  Can you move it to `umka-lang`? 
@skejeton Could you please share your idea of where the embedded modules should be?

**Comment by marekmaskarinec** [comment]
I can only move the issue to repos I own.

**Comment by skejeton** [comment]
@vtereshkov i think it should be indicative that module is embedded, common practice is to prepend `@` before the module like this: `import ("@std/map.um")` or some alternate prefix: `import("#std/map.um")` or something that won't conflict with filenames `import ("embed://std/map.um") // BOO - tedious`. Otherwise I think it's fine as it is - lua got away with that, at least

**Comment by vtereshkov** [comment]
@skejeton I'm afraid prefixes such as `#` or `@` do not follow the principle of least astonishment. What should a new user expect from such a prefix? Of course, the C-like syntax of Umka is full of such non-intuitive punctuation, but, thanks to C, we have had enough time (50 years) to get familiar with it.

Anyway, this issue is not related to `tophat`. If you find it important, please reopen it in `umka-lang`.

**Comment by marekmaskarinec** [comment]
> @vtereshkov i think it should be indicative that module is embedded, common practice is to prepend @ before the module like this: import ("@std/map.um") or some alternate prefix: import("#std/map.um") or something that won't conflict with filenames import ("embed://std/map.um") // BOO - tedious. Otherwise I think it's fine as it is - lua got away with that, at least

Personally I don't see this as a problem and this is an umka issue anyways.
