### ISSUE TITLE
Tophat, Tophat-fusion

### ISSUE THREAD

**Issue by muhammadharoon786** [marekmaskarinec/tophat#56]
How can I solve this error? I want to run the Tophat for the CIRIexporer2 related work. When I run Tophat, it does not work without running the Tophat module. So when I run both modules together, I face the below mentioned problem. Please suggest  me a solution. I am not expert in bioinformatics. Thanks!

$ module load Bowtie2 Tophat
Python/2.7.15(14):ERROR:150: Module 'Python/2.7.15' conflicts with the currently loaded module(s) 'Python/3.6.5'
Python/2.7.15(14):ERROR:102: Tcl command execution failed: conflict Python

**Comment by marekmaskarinec** [comment]
are you talking about the correct tophat?

**Comment by skejeton** [comment]
Yes indeed I think they got the wrong one.. 

@muhammadharoon786 You might want to refer to http://ccb.jhu.edu/software/tophat/ or
https://github.com/BenLangmead/bowtie2 instead. 

This repository is for tophat game library, sorry for confusion.

**Comment by muhammadharoon786** [comment]
thanks all. I am sorry for poasting here. But If somebody knows the answer, please suggest. I am talking about the tophat which is used for the sequencing analysis of genomes.

**Comment by skejeton** [comment]
No worries.

I don't know much about python and especially biotech, but it seems like your python versions are conflicting. Try running `module unload 'Python/3.6.5'` before running `module load Bowtie2 Tophat`. Good luck.
