### ISSUE TITLE
incorrect attribute names in c

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#57]
The program starts normally and stays open, but only shows a white window. It also seems like this only happens on some machines. Older versions work.

**Comment by marekmaskarinec** [comment]
This issue is caused by the new shader support. I think its because I use glsl function prototypes, which some gpu drivers might not support. It should however be possible to place the user data first.

**Comment by vtereshkov** [comment]
@marekmaskarinec If you wish, I can test tophat on my Windows machine to collect debug logs or something.

**Comment by marekmaskarinec** [comment]
The problem is there are no debug logs. The shaders don't work, but the driver doesn't report any logs. I tried using a recent glsl version and getting rid of the function prototypes (which I read some drivers don't support), but with no success.

**Comment by marekmaskarinec** [comment]
I updated the names of attributes in the shaders to have a `th_` prefix, but didn't update them in the c source code. Strangely it worked on some drivers.
