### ISSUE TITLE
Packaging Tophat as an Umka extension

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#6]
Did you consider packaging Tophat as an Umka Module Implementation (UMI) library? An UMI file is a conventional precompiled C/C++ shared library that has the `.umi` extension. When the Umka interpreter encounters a function prototype that has no implementation in Umka, it automatically searches for the UMI library in the same directory. If the library is found, Umka links it dynamically and looks for the function implementations.

This mechanism would allow running Umka games using the basic Umka interpreter instead of the custom `tophat` executable. What it does not support is calling Umka functions from C/C++.

An example of using an UMI library is [here](https://github.com/vtereshkov/umka-lang/tree/master/tests/lib) and [here](https://github.com/vtereshkov/umka-lang/blob/master/tests/extlib.um).

**Comment by marekmaskarinec** [comment]
I don't think, that would be beneficial, since the user would need to install the umka interpreter. There is also stuff like input, that could not work. I'm happy with the solution I have rn. Until I implement some way to embedd assets, I plan on keeping it.

**Comment by vtereshkov** [comment]
Okay, I understand.
