### ISSUE TITLE
Images should free upon GC

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#69]
best example is calling 
```
  img := image.mk(screenData, th.Vf2{200, 200})
  img.draw(th.Transform{s: th.Vf2{1, 1}})
```
repeatedly, it drains the RAM very quickly. This is important for there's no way to free an image. Ideally this shouldn't be manual as umka is a GC language.

**Comment by marekmaskarinec** [comment]
Freeing images using GC would require a rework of how opaque structures are stored.

For your specific usecase, the new `Image.setData` method could be useful.

**Comment by vtereshkov** [comment]
The main question is: who owns the image? If it's the host application, you cannot deallocate it with Umka's GC.

**Comment by marekmaskarinec** [comment]
Tophat owns all opaque data. Allocating them in umka would be possible if it's necessarily needed.

**Comment by skejeton** [comment]
How lua handles this approach is it gives out a custom malloc function. However there's also another approach it provides, notifying when the item is about to be collected. In lua it's implemented via metatable. In umka in my opinion, this could be done by allowing to implement `free` method function, or use an existing keyword for like `delete`. Roughly how this would look like:

```
fn (i: ^Image) delete() { // or free, whatever
  imgfree(i.handle)
}
```

**Comment by skejeton** [comment]
Done
