### ISSUE TITLE
Exposing tophat API in UMI modules

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#70]
As we know umka provides .umi modules to embed snippets of native code in umka, and it works great if you are using it for resource intensive tasks, however if you want to access the internals of umka or tophat you have to link them again, without any ABI guarantees. I think it's worth adding a way to build tophat as .so/.dll + launcher executable so umi modules can link to it too and access umka's or tophat's API and add necessary functionality

**Comment by marekmaskarinec** [comment]
I wanted to do this for a long time. Shipping tophat as a dynamic library should work. We would need to share the `th_global` between all the tophats but that shouldn't be a problem.

**Comment by vtereshkov** [comment]
See also #6

**Comment by marekmaskarinec** [comment]
I would also have to put all the global variables into `th_global`.
