### ISSUE TITLE
input.isReleased

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#71]
for detecting if the keys were released or not, for now the workaround is to create a custom input state and check against it, but that's not very convenient

**Comment by marekmaskarinec** [comment]
`input.isReleased` is just `!input.isJustPressed`. I can implement `input.isJustReleased`.

**Comment by skejeton** [comment]
That's what i meant yes. isJustReleased seems to be a more consistent name so go with that.
