### ISSUE TITLE
Crash when image not found

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#72]
```
  bevelImage = image.load("data/ts04_belvelbutton.png")
  printf("h-hello?")
```

the print statement is never executed if the image path wasn't correct, segmentation fault occurs.

**Comment by marekmaskarinec** [comment]
Does it atleast print the error message?

**Comment by skejeton** [comment]
Yes it does print that it failed to load

**Comment by skejeton** [comment]
Here's a demonstration
https://user-images.githubusercontent.com/27076041/183398590-659aa088-057b-4889-926b-56b2f52d543d.mp4

**Comment by skejeton** [comment]
The issue was fixed but not marked as such
