### ISSUE TITLE
Layered drawing.

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#83]
Rendering currently only displays the things in order they are drawn, but this is sometimes inconvenient. For example:

```
BeginWindow("WindowA")
  //...
BeginWindow("WindowB")
  //...
BeginWindow("WindowC")
  //...
```

The windows will be drawn in order of A B and C, but if we drag the window A on top, it will still be rendered behind window B and C because it appears before them in code. 

This currently can be worked around with a draw command system, where the drawing code is deferred and then actually rendered. But it's not very useful to have draw commands for every single thing you want to draw. There's an alternative workaround, rendering windows with callback: 
```
BeginWindow("WindowA", fn(data: interface{}) {

}, data)
```

I currently know of 2 ways to work with this: access to depth buffer, sorting draw calls into layers.

**Comment by marekmaskarinec** [comment]
I never planned for something like this to be included in tophat. For me the callback idea is much better than adding more features to the engine, although Umka's lack of closures might make it harder to work with.

**Comment by skejeton** [comment]
Definitely. I'll go with the callbacks for now, but i can see the appeal for maybe having access to the depth buffer

**Comment by skejeton** [comment]
As for the callback idea. The problem struck with nested callbacks. In the end I decided against that idea since everything was completely out of order.

**Comment by skejeton** [comment]
Currently I'm going with a draw command buffer idea, and it's working somewhat. I pass in an interface to add custom drawing functions

**Comment by skejeton** [comment]
Closing thus far as it's pretty vague. But would love to have layered drawing of some kind. In my opinion this would be especially important once we can maybe get cached renderer to work.

**Comment by skejeton** [comment]
.
