### ISSUE TITLE
Memory leaks in `umsoundplay()` if called too frequently

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#84]
How to reproduce:
* Run the tetris example
* Hit a rotation (Z, X, C) or drop (space) key several times very quickly
* Close the program window
* See memory leak warnings

**Comment by skejeton** [comment]
Looks like the problem is unnecessary increment:https://github.com/marekmaskarinec/tophat/blob/main/src/bindings.c#L352

**Comment by skejeton** [comment]
I can see why it was put there, it creates issue of memory leaks but it solves the problem of the object getting freed after being discarded. The way to solve this is probably to allocate the handle instead

**Comment by vtereshkov** [comment]
@skejeton Notice that this leak never happens if the function is called not too often (so that the sound plays to the end and stops normally?)

**Comment by skejeton** [comment]
Yeah it seems to only happen when the sound didn't finish playing entirely

**Comment by marekmaskarinec** [comment]
> Notice that this leak never happens if the function is called not too often (so that the sound plays to the end and stops normally?)

This is weird, since adding more playbacks shouldn't affect other playbacks.

> Looks like the problem is unnecessary increment:
https://github.com/marekmaskarinec/tophat/blob/main/src/bindings.c#L352

This is since the `thg.playbacks` own a reference. It is decremented when the sound stop playing.

**Comment by vtereshkov** [comment]
> This is weird, since adding more playbacks shouldn't affect other playbacks.

But what if all those playbacks refer to the same `audio.Sound`?

**Comment by marekmaskarinec** [comment]
Playbacks don't refer to `audio.Sound`s at all.

**Comment by vtereshkov** [comment]
@marekmaskarinec `prev = pbi;` is missing from the `for` loop in `_th_audio_data_callback()`, so it cannot process lists longer than one sound.

**Comment by marekmaskarinec** [comment]
> @marekmaskarinec prev = pbi; is missing from the for loop in _th_audio_data_callback(), so it cannot process lists longer than one sound.

This might have been the problem. I fixed it and now I can't reproduce neither the memory leak warnings or the sound cutting of too early issue.

**Comment by vtereshkov** [comment]
Great!
