### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#9]
```
C:\Users\Vasiliy\AppData\Local\Temp\cccrotWu.o:bindings.c:(.text+0xb89): undefined reference to `RotatePoint'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:21: windows] Error 1
```

**Comment by marekmaskarinec** [comment]
Try running this: `git submodule update --recursive --remote`

**Comment by vtereshkov** [comment]
Thank you. It works. By the way, do you update `lib/windows/libumka_static.a` automatically? It seems to be outdated and not identical to what can be built from `lib/umka`.

**Comment by marekmaskarinec** [comment]
No. I don't update it. How do I build it on linux?

**Comment by vtereshkov** [comment]
OK. So I do the right thing when I manually copy `libumka_static.a` from `lib/umka/umka_windows_mingw` to `lib/windows`.

**Comment by marekmaskarinec** [comment]
I think yes.

**Comment by ProkopRandacek** [comment]
btw @marekmaskarinec this can be solved automatically in makefile by checking if the submodule's files exists and if not you can run `git submodule update --init --recursive`.

https://github.com/ProkopRandacek/r8/blob/7d9c4a34c262fc1ed8e011065f30ad0d7d46cb49/Makefile#L79

**Comment by marekmaskarinec** [comment]
That's only one part of the issue. The issue here was, he had an old version of the submodule.
