### ISSUE TITLE
Calling window.setup twice causes crash on exit

### ISSUE THREAD

**Issue by skejeton** [marekmaskarinec/tophat#95]
It creates 2 windows, and crashes the program after you close it. It should ideally just change the current window's title and size.

**Comment by marekmaskarinec** [comment]
I don't think calling the setup function again should change the properties of the window. What if you want to change only the title?

I will fix the bug and make separate functions for window properties.

**Comment by marekmaskarinec** [comment]
It might be worth it adding the ability to manage multiple windows, but that would require some overhauls.

**Comment by skejeton** [comment]
> I don't think calling the setup function again should change the properties of the window. What if you want to change only the title?
> 
> I will fix the bug and make separate functions for window properties.

You can just put in current values

**Comment by skejeton** [comment]
#97
