### ISSUE TITLE
`window.setDims`, `window.setTitle`, `window.setIcon`

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#97]
#95

**Comment by marekmaskarinec** [comment]
> > I don't think calling the setup function again should change the properties of the window. What if you want to change only the title?
> 
> You can just put in current values

That's true, but I think having separate functions will be easier for the user.

**Comment by skejeton** [comment]
No problem then

**Comment by marekmaskarinec** [comment]
@skejeton could you please implement these functions on windows?
