### ISSUE TITLE
Avoid mutable strings

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#98]
Mutable strings are no longer allowed in Umka. Please fix tophat accordingly.

For example, change
```
fn loadimg(ret: ^Image, path: ^char)
```
to
```
fn loadimg(ret: ^Image, path: str)
```
and just call `loadimg(&img, path)`.

Also, you can rewrite `toupper()` and `tolower()` as
```
fn toupper*(inp: str): str {
    l := len(inp)
    out := make([]char, l)
	for i:=0; i < l; i++ {
		out[i] = chartoupper(inp[i])
	}
	return str(out)
}
```
No other occurences found so far.

CC @skejeton

**Comment by skejeton** [comment]
Hi. I don't use mutable strings.

**Comment by vtereshkov** [comment]
@skejeton Actually you do it in `makeUppercase()`.
